<script setup>
defineProps({ analytics: Object, analyticsPeriod: String, fallbackYoutubeIds: Object, loadingAddToFallback: Object })
defineEmits(['period', 'add-fallback'])
</script>
<template>
  <div>
    <div class="an-period"><button v-for="p in [{k:'day',l:'Hoy'},{k:'week',l:'Semana'},{k:'month',l:'Mes'},{k:'all',l:'Todo'}]" :key="p.k" class="an-period-btn" :class="{ active: analyticsPeriod === p.k }" @click="$emit('period', p.k)">{{ p.l }}</button></div>
    <div v-if="analytics"><div class="an-grid"><div class="an-card"><p class="an-val">{{ analytics.summary.total_songs_played }}</p><p class="an-label">Canciones</p></div><div class="an-card"><p class="an-val">{{ analytics.summary.unique_users }}</p><p class="an-label">Usuarios</p></div><div class="an-card"><p class="an-val">{{ analytics.summary.unique_songs }}</p><p class="an-label">Unicas</p></div><div class="an-card"><p class="an-val">{{ analytics.summary.avg_queue_length }}</p><p class="an-label">Prom. Cola</p></div><div class="an-card" v-if="analytics.summary.active_days !== undefined"><p class="an-val">{{ analytics.summary.active_days }}</p><p class="an-label">Dias activos</p></div><div class="an-card" v-if="analytics.summary.skip_count !== undefined"><p class="an-val">{{ analytics.summary.skip_count }} <small>({{ analytics.summary.skip_rate }}%)</small></p><p class="an-label">Skips</p></div><div class="an-card" v-if="analytics.summary.error_count !== undefined"><p class="an-val">{{ analytics.summary.error_count }} <small>({{ analytics.summary.error_rate }}%)</small></p><p class="an-label">Errores</p></div><div class="an-card" v-if="analytics.summary.fallback_activations !== undefined"><p class="an-val">{{ analytics.summary.fallback_activations }}</p><p class="an-label">Fallbacks</p></div><div class="an-card" v-if="analytics.summary.new_users !== undefined"><p class="an-val">{{ analytics.summary.new_users }}</p><p class="an-label">Nuevos</p></div><div class="an-card" v-if="analytics.summary.returning_users !== undefined"><p class="an-val">{{ analytics.summary.returning_users }}</p><p class="an-label">Recurrentes</p></div></div>
      <div class="card" v-if="analytics.top_songs.length"><p class="section-title">TOP CANCIONES</p><div v-for="(s, i) in analytics.top_songs" :key="s.youtube_id" class="an-song"><span class="an-pos">{{ i + 1 }}</span><img :src="`https://i.ytimg.com/vi/${s.youtube_id}/mqdefault.jpg`" class="an-thumb" /><span class="an-title">{{ s.title }}</span><span class="an-count">{{ s.times_played }}x</span><button class="q-btn-label q-btn-fallback" @click="$emit('add-fallback', s.youtube_id)" :disabled="fallbackYoutubeIds.has(s.youtube_id) || loadingAddToFallback[s.youtube_id]">{{ loadingAddToFallback[s.youtube_id] ? '...' : fallbackYoutubeIds.has(s.youtube_id) ? '&#10003; En respaldo' : '+ Respaldo' }}</button></div></div>
      <div class="card" v-if="analytics.top_artists && analytics.top_artists.length" style="margin-top:12px;"><p class="section-title">TOP ARTISTAS</p><div v-for="(a, i) in analytics.top_artists" :key="a.artist" class="an-song"><span class="an-pos">{{ i + 1 }}</span><span class="an-title">{{ a.artist }}</span><span class="an-count">{{ a.count }}x</span></div></div>
      <div class="card" v-if="analytics.peak_hours.length" style="margin-top:12px;"><p class="section-title">HORAS PICO</p><div v-for="h in analytics.peak_hours.slice(0, 8)" :key="h.hour" class="an-hour"><span class="an-hour-label">{{ h.hour }}</span><div class="an-hour-bar"><div class="an-hour-fill" :style="{ width: (h.requests / analytics.peak_hours[0].requests * 100) + '%' }"></div></div><span class="an-hour-count">{{ h.requests }}</span></div></div>
      <div class="card" v-if="analytics.top_tables && analytics.top_tables.length" style="margin-top:12px;"><p class="section-title">USUARIOS MAS ACTIVOS</p><div v-for="(t, i) in analytics.top_tables" :key="t.table_number" class="an-song"><span class="an-pos">{{ i + 1 }}</span><span class="an-title">{{ t.table_number }}</span><span class="an-count">{{ t.total_songs }} canciones</span></div></div></div>
    <div v-else class="card"><p class="text-muted">Cargando analytics...</p></div>
  </div>
</template>
