<script setup>
import Badge from '../ui/Badge.vue'
import UiInput from '../ui/Input.vue'

defineProps({
  billing: { type: Object, required: true }, visibleHistory: { type: Array, required: true }, showAllHistory: Boolean,
  editingEventId: { type: [String, Number], default: null }, editingNoteText: { type: String, default: '' }, editingAmountCOP: { type: String, default: '' }, editingDate: { type: String, default: '' }, savingNote: Boolean, voidingEventId: { type: [String, Number], default: null },
})
defineEmits(['toggle-history', 'start-edit', 'void', 'save', 'cancel', 'update:editingNoteText', 'update:editingAmountCOP', 'update:editingDate'])

const currency = new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 })
const formatDate = value => value ? new Date(`${value.slice(0, 10)}T00:00:00`).toLocaleDateString('es-CO', { day: 'numeric', month: 'short', year: 'numeric' }) : ''
function eventTitle(item) { if (item.kind === 'payment') return currency.format((item.amount_cents || 0) / 100); if (item.kind === 'trial') return `Prueba +${item.days || 0} días`; if (item.kind === 'adjustment') return item.days == null ? 'Ajuste de vencimiento' : `Ajuste de vencimiento (${item.days > 0 ? '+' : ''}${item.days} días)`; return 'Registro previo' }
const canEditAmount = item => item.kind === 'payment' && item.source === 'manual' && item.status !== 'voided'
const canEditDate = item => (item.kind === 'payment' || item.kind === 'trial') && item.source === 'manual' && item.status !== 'voided'
</script>

<template>
  <div class="history-section">
    <div class="history-header"><p class="history-title">HISTORIAL ({{ billing.history?.length || 0 }})</p><button v-if="billing.history?.length > 4" type="button" class="toggle-history-btn" @click="$emit('toggle-history')">{{ showAllHistory ? 'Ver menos' : `Ver todos (${billing.history.length})` }}</button></div>
    <div v-if="visibleHistory.length" class="history-list">
      <div v-for="item in visibleHistory" :key="item.id || item.created_at" class="history-card" :class="{ 'history-card-voided': item.status === 'voided' }">
        <div class="history-line-1"><div class="history-main-label"><strong :class="item.kind === 'adjustment' ? 'adjustment-amount' : item.kind === 'legacy' ? 'legacy-amount' : 'payment-amount'">{{ eventTitle(item) }}</strong></div><div class="history-right-wrap"><div class="history-badges"><Badge v-if="item.source === 'wompi'" variant="info">Wompi</Badge><Badge v-else-if="item.kind === 'adjustment'" variant="warning">Ajuste · {{ item.created_by_username || 'Admin' }}</Badge><Badge v-else-if="item.source === 'manual'" variant="neutral">Manual · {{ item.created_by_username || 'Admin' }}</Badge><Badge v-else-if="item.source === 'legacy'" variant="neutral">Histórico</Badge><Badge v-else-if="item.source" variant="neutral">{{ item.source }}</Badge><Badge v-if="item.status === 'voided'" variant="danger">Anulado</Badge><Badge v-else-if="item.status === 'declined'" variant="danger">Rechazado</Badge><Badge v-else-if="item.status === 'pending'" variant="warning">Pendiente</Badge></div><div v-if="item.status !== 'voided' && item.source !== 'wompi'" class="item-actions"><button type="button" class="action-icon-btn" title="Editar nota" aria-label="Editar nota" @click="$emit('start-edit', item)">✎</button><button type="button" class="action-icon-btn action-void-btn" :disabled="voidingEventId === item.id" title="Anular movimiento" aria-label="Anular movimiento" @click="$emit('void', item)">×</button></div></div></div>
        <div class="history-line-2"><span>{{ formatDate(item.created_at) }}</span><span v-if="item.days && item.kind !== 'adjustment'">· {{ item.days }} días</span><span v-if="item.period_start && item.period_end">· {{ formatDate(item.period_start) }} → {{ formatDate(item.period_end) }}</span><span v-if="item.provider_ref" class="provider-ref" :title="item.provider_ref">· ref {{ item.provider_ref }}</span></div>
        <div v-if="editingEventId === item.id" class="note-edit-row"><UiInput v-if="canEditAmount(item)" :model-value="editingAmountCOP" type="number" inputmode="numeric" placeholder="Monto COP..." aria-label="Editar monto en pesos COP" class="edit-inline-amount" @update:model-value="$emit('update:editingAmountCOP', $event)" @keydown.esc="$emit('cancel')" /><UiInput v-if="canEditDate(item)" :model-value="editingDate" type="date" aria-label="Editar fecha de fin del período" class="edit-inline-date" @update:model-value="$emit('update:editingDate', $event)" @keydown.esc="$emit('cancel')" /><UiInput :model-value="editingNoteText" placeholder="Nota del movimiento..." aria-label="Editar nota del movimiento" class="note-inline-input" @update:model-value="$emit('update:editingNoteText', $event)" @keydown.enter="$emit('save', item)" @keydown.esc="$emit('cancel')" /><div class="note-inline-buttons"><button type="button" class="note-btn note-save-btn" :disabled="savingNote" title="Guardar nota" aria-label="Guardar nota" @click="$emit('save', item)">✓</button><button type="button" class="note-btn note-cancel-btn" :disabled="savingNote" title="Cancelar edición" aria-label="Cancelar edición" @click="$emit('cancel')">✕</button></div></div>
        <div v-else-if="item.notes" class="history-line-3">{{ item.notes }}</div>
      </div>
    </div>
    <p v-else class="history-empty">Sin movimientos registrados</p>
  </div>
</template>

<style scoped>
.history-section,.history-list { display:flex; flex-direction:column; gap:10px; }.history-header,.history-line-1,.history-right-wrap,.history-badges,.item-actions,.history-line-2,.note-edit-row,.note-inline-buttons { display:flex; align-items:center; gap:8px; }.history-header,.history-line-1 { justify-content:space-between; }.history-title { margin:0; color:var(--text-muted); font-size:11px; font-weight:700; letter-spacing:.5px; }.toggle-history-btn { background:transparent; border:0; color:var(--primary); font-size:12px; font-weight:600; cursor:pointer; padding:2px 4px; }.toggle-history-btn:hover { text-decoration:underline; }.history-card { background:var(--bg-elevated); border-radius:var(--radius-sm,8px); padding:10px 12px; display:flex; flex-direction:column; gap:4px; }.history-card-voided { opacity:.55; }.history-card-voided strong { text-decoration:line-through; }.payment-amount { font-size:14px; font-weight:700; }.adjustment-amount { font-size:13px; font-weight:700; color:var(--warning); }.legacy-amount,.history-line-2,.history-line-3 { font-size:12px; color:var(--text-muted); }.legacy-amount { font-size:13px; font-weight:600; }.action-icon-btn,.note-btn { border:1px solid var(--border); background:transparent; color:var(--text-muted); cursor:pointer; }.action-icon-btn { width:24px; height:24px; border-radius:4px; }.action-void-btn:hover { color:var(--danger); border-color:var(--danger); }.history-line-2 { gap:4px; flex-wrap:wrap; font-variant-numeric:tabular-nums; }.provider-ref { font-family:ui-monospace,monospace; font-size:11px; overflow-wrap:anywhere; }.history-line-3 { font-style:italic; margin-top:2px; word-break:break-word; }.note-edit-row { gap:6px; margin-top:4px; flex-wrap:wrap; }.note-inline-input { flex:1; min-width:140px; }.edit-inline-amount { flex:0 0 110px; }.edit-inline-date { flex:0 0 130px; }.note-btn { width:26px; height:26px; border-radius:4px; font-weight:700; }.note-save-btn { background:var(--success-soft); color:var(--success); }.history-empty { text-align:center; padding:16px 0; color:var(--text-muted); font-size:13px; margin:0; }
@media (max-width:360px) { .history-line-1 { flex-direction:column; align-items:flex-start; gap:6px; }.history-right-wrap { width:100%; justify-content:space-between; } }
</style>
