export const THEME_PRESETS = [
  {
    id: 'purple-night',
    name: 'Noche Morada',
    tokens: 'purple-night',
    accent: '#6C5CE7',
    mode: 'dark',
    colors: { bg: '#0F0F1A', text: '#EAEAEA' },
  },
  {
    id: 'red-fire',
    name: 'Fuego Rojo',
    tokens: 'red-fire',
    accent: '#E74C3C',
    mode: 'dark',
    colors: { bg: '#1A0F0F', text: '#EAEAEA' },
  },
  {
    id: 'green-jungle',
    name: 'Selva Verde',
    tokens: 'green-jungle',
    accent: '#00B894',
    mode: 'dark',
    colors: { bg: '#0F1A15', text: '#EAEAEA' },
  },
  {
    id: 'blue-ocean',
    name: 'Oceano Azul',
    tokens: 'blue-ocean',
    accent: '#0984E3',
    mode: 'dark',
    colors: { bg: '#0F131A', text: '#EAEAEA' },
  },
  {
    id: 'gold-elegance',
    name: 'Elegancia Dorada',
    tokens: 'gold-elegance',
    accent: '#F39C12',
    mode: 'dark',
    colors: { bg: '#1A170F', text: '#EAEAEA' },
  },
  {
    id: 'craft-dark',
    name: 'Artesanal Oscuro',
    // Paleta completa en src/themes/craft.css (no se deriva nada en runtime)
    tokens: 'craft',
    accent: '#D2B56F',
    mode: 'dark',
    colors: { bg: '#12100E', text: '#FFF8E9' },
  },
  {
    id: 'purple-light',
    name: 'Morado Claro',
    tokens: 'purple-light',
    accent: '#6C5CE7',
    mode: 'light',
    colors: { bg: '#F4F4F8', text: '#1A1A2E' },
  },
  {
    id: 'red-light',
    name: 'Rojo Claro',
    tokens: 'red-light',
    accent: '#E74C3C',
    mode: 'light',
    colors: { bg: '#FDF4F4', text: '#1A1A2E' },
  },
  {
    id: 'green-light',
    name: 'Verde Claro',
    tokens: 'green-light',
    accent: '#00B894',
    mode: 'light',
    colors: { bg: '#F0FAF7', text: '#1A1A2E' },
  },
  {
    id: 'blue-light',
    name: 'Azul Claro',
    tokens: 'blue-light',
    accent: '#0984E3',
    mode: 'light',
    colors: { bg: '#F0F6FD', text: '#1A1A2E' },
  },
  {
    id: 'gold-light',
    name: 'Dorado Claro',
    tokens: 'gold-light',
    accent: '#F39C12',
    mode: 'light',
    colors: { bg: '#FDFAF0', text: '#1A1A2E' },
  },
  {
    id: 'craft-light',
    name: 'Artesanal Claro',
    // Paleta completa en src/themes/craft.css (no se deriva nada en runtime)
    tokens: 'craft',
    accent: '#5C3A26',
    mode: 'light',
    colors: { bg: '#F7EFDD', text: '#33241A' },
  },
]
